### ISSUE TITLE
Split test tasks of a gradle file.

### ISSUE THREAD

**Issue by luigiocone** [luigiocone/tepaci#1]
* *As a* user
* *I want to* split several test tasks in a gradle file
* *So that* I can run a single test indipendently of others

**Details**: Create a new Gradle file from an existing one that accepts a custom scaffolding structure. E.g., through this new file, gradle should be able to run those tasks:
```
> gradle customTest01
> gradle customTest02
```

**Tasks:**
- [x] Add functionality for line scanning the file until a significant group or EOF
- [x] Scanning file should also track the already inserted "task"
- [x] Add functionality for adding tasks, source sets, configurations, into a memory buffer
- [x] Add functionality for writing all buffered informations in a new gradle file, preserving the old gradle file build configuration
- [x] Write JUnit tests
